### ISSUE TITLE
Support HTTP discovery endpoints

### ISSUE THREAD

**Issue by tanelsuurhans** [nov/SWD#1]
Instead of defaulting to the URI::HTTPS builder and ignoring the provider URLs scheme, it seems to make more sense to use URI::HTTP and just pass in the scheme - in which case if the discovery endpoint provided uses HTTPS, it will be supported as such. Same for HTTP. I realize that enforcing SSL is a good practice for security, but it makes local development quite painful with your openid_connect library.

**Comment by nov** [comment]
Do something like this.
https://github.com/nov/openid_connect_sample_rp/blob/master/config/initializers/debugger.rb

WebFinger (and SWD) requires HTTPS, and not allowing HTTP.
